-- 创建邀请码表
CREATE TABLE IF NOT EXISTS invite_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(9) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_invite_codes_date ON invite_codes(date);
CREATE INDEX IF NOT EXISTS idx_invite_codes_code ON invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_used ON invite_codes(used);

-- 启用 Row Level Security (RLS)
ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;

-- 创建允许所有操作的策略（开发环境）
CREATE POLICY "Allow all operations" ON invite_codes
    FOR ALL
    USING (true)
    WITH CHECK (true);